export const GET_BOOKS = 'GET_BOOKS';

export const BOOK_POPUP_OPEN = 'BOOK_POPUP_OPEN';
export const BOOK_POPUP_CLOSE = 'BOOK_POPUP_CLOSE';

export const PRELOADER_SHOW = 'PRELOADER_SHOW';
export const PRELOADER_HIDE = 'PRELOADER_HIDE';